// Load HAL
#include "includes.h"

#include "records.h"
#include "contacts.h"

/*
  Read the contacts and message stream generated by the stim, and put
  it all into to the D81s for the phone state.

  Linux only for testing for now.
  But it could later become part of a native backup and restore facility.
*/

void usage(void)
{
  fprintf(stderr,"usage: export <output.txt>\n");
  exit(-1);
}

char to_hex(unsigned char v)
{
  v&=0xf;
  if (v<0xa) return v+'0';
  if (v>0xf) return 0;
  return 'A'+(v-0xa);
}

int main(int argc,char **argv)
{
  if (argc!=2) {
    usage();
  }
  
  FILE *f=fopen(argv[1],"wb");
  
  hal_init();

  // CONTACT:+99920915060:Jerry:Williams:
  // MESSAGERX:+99973014512:397831207:🤣🎧🐨💻🥭 Id nisi MEGA65 corrupti natus:
  // MESSAGETX:+99966049372:397833622:🍳🍿 Quasi nisi quidem, quis veniam sed numquam ipsam quo hic amet molestiae? Veritatis cupiditate ullam nihil et tenetur doloribus, accusantium:

  mega65_cdroot();
  mega65_chdir("PHONE");

  int disk_images=0;
  for(int i=0;i<10;i++) {
    char filename[16];
    snprintf(filename,sizeof(filename),"CONTACT%d.D81",i);
    if (mount_d81(filename,0)) {
      continue;
    }
    disk_images++;

    // Contacts begin in sector 1 of the disk, with ID 1 (sector/ID 0 = record BAM)
    for(int c=1;c<USABLE_SECTORS_PER_DISK;c++) {

      // This used to have a field for it. Maybe we'll have to go back to that, but 
      unsigned int qso_number = i * USABLE_SECTORS_PER_DISK + c;
      
      unsigned char contact[RECORD_DATA_SIZE];
      char r = read_contact_by_id(0,c,contact);
      if (!r) {
	unsigned int firstNameLen = 0;
	unsigned char *firstName = find_field(contact,RECORD_DATA_SIZE,FIELD_FIRSTNAME,&firstNameLen);
	unsigned int lastNameLen = 0;
	unsigned char *lastName = find_field(contact,RECORD_DATA_SIZE,FIELD_LASTNAME,&lastNameLen);
	unsigned int phoneNumberLen = 0;
	unsigned char *phoneNumber = find_field(contact,RECORD_DATA_SIZE,FIELD_PHONENUMBER,&phoneNumberLen);
	unsigned int unreadCountLen = 0;
	unsigned char *unreadCount = find_field(contact,RECORD_DATA_SIZE,FIELD_UNREAD_MESSAGES,&unreadCountLen);

	unsigned int unreadCountVal = 0;
	if (unreadCount) {
	  unreadCountVal = unreadCount[0] + (unreadCount[1]<<8);
	}
	
	if (firstName||lastName||phoneNumber||unreadCount) {
	  fprintf(f,"CONTACT:%s:%s:%s:%d:\n",
		  phoneNumber?(char *)phoneNumber:"",
		  firstName?(char *)firstName:"",
		  lastName?(char *)lastName:"",
		  unreadCountVal);
	}
      }
    }
  }

  fclose(f);
  
  return 0;
}
