// Load HAL
#include "includes.h"

#include "records.h"
#include "contacts.h"

/*
  Read the contacts and message stream generated by the stim, and put
  it all into to the D81s for the phone state.

  Linux only for testing for now.
  But it could later become part of a native backup and restore facility.
*/

void usage(void)
{
  fprintf(stderr,"usage: stim-import <stim_file.txt>\n");
  exit(-1);
}

char to_hex(unsigned char v)
{
  v&=0xf;
  if (v<0xa) return v+'0';
  if (v>0xf) return 0;
  return 'A'+(v-0xa);
}

int main(int argc,char **argv)
{
  if (argc!=2) {
    usage();
  }
  
  FILE *f=fopen(argv[1],"rb");
  
  hal_init();
  mega65_chdir("PHONE");

  char line[1024];

  // Fields for contacts
  unsigned char firstName[1024];
  unsigned char lastName[1024];
  unsigned char phoneNumber[1024];

  line[0]=0; fgets(line,1024,f);
  while(line[0]) {
    // CONTACT:+99920915060:Jerry:Williams:
    if (sscanf(line,"CONTACT:%[^:]:%[^:]:%[^:]",
	       phoneNumber,firstName,lastName)==3) {
      // Found a contact.
      unsigned char buffer[508];
      unsigned int bytes_used=0;
      if (build_contact(buffer,&bytes_used,
			firstName,lastName,phoneNumber)) {
	fprintf(stderr,"ERROR: Failed to parse contact line: %s\n",line);
      } else {
	mega65_cdroot();
	mega65_chdir("PHONE");
	mount_d81("CONTACT0.D81",0);
	dump_sector_buffer("Before read BAM");
	read_sector(0,1,0);
	dump_sector_buffer("After read BAM");
	unsigned int record_number = record_allocate_next( (unsigned char *)SECTOR_BUFFER_ADDRESS );
	if (!record_number) {
	  fprintf(stderr,"ERROR: Failed to allocate contact record for: %s\n",line);
	} else {
	  // Write back updated BAM
	  write_sector(0,1,0);
	  // Allocated record, so write contact
	  char r=write_contact_by_id(0,record_number,buffer);
	  if (r) {
	    fprintf(stderr,"ERROR: Failed to write contact to record #%d (code %d)\n",record_number,r);
	  }
	}
      }
    } else {
      fprintf(stderr,"ERROR: Could not scan line: %s\n",line);
      exit(-1);
    }
    
    line[0]=0; fgets(line,1024,f);
  }

  // XXX - Update sorted versions of contacts
  // XXX - Update search index for contacts
  
}
